version: '3'
services:

  edbm:
    build:
      context: .
    ports:
      - "8000:8000"

  db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: arutv