# Generated by Django 2.1.5 on 2019-05-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentwithtitle',
            table=None,
        ),
    ]
